mediapipe:
  model_complexity: 2
  min_detection_confidence: 0.5
  min_tracking_confidence: 0.5

model:
  n_estimators: 100
  max_depth: 10
  random_state: 42
  features: ['x_norm', 'y_norm', 'visibility', 'center_x', 'center_y', 'unit_length']
  exercise_types: ['pushup', 'squat', 'long_jump']
  correctness_thresholds:
    min_visibility: 0.5